/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics/index'
import { Route as TopicsTopicSlugIndexRouteImport } from './routes/topics/$topicSlug/index'
import { Route as TopicsTopicSlugVideoRouteImport } from './routes/topics/$topicSlug/video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicSlugIndexRoute = TopicsTopicSlugIndexRouteImport.update({
  id: '/topics/$topicSlug/',
  path: '/topics/$topicSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicSlugVideoRoute = TopicsTopicSlugVideoRouteImport.update({
  id: '/topics/$topicSlug/video',
  path: '/topics/$topicSlug/video',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/topics/$topicSlug/video': typeof TopicsTopicSlugVideoRoute
  '/topics/$topicSlug/': typeof TopicsTopicSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/topics': typeof TopicsIndexRoute
  '/topics/$topicSlug/video': typeof TopicsTopicSlugVideoRoute
  '/topics/$topicSlug': typeof TopicsTopicSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/topics/$topicSlug/video': typeof TopicsTopicSlugVideoRoute
  '/topics/$topicSlug/': typeof TopicsTopicSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/topics/'
    | '/topics/$topicSlug/video'
    | '/topics/$topicSlug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/topics' | '/topics/$topicSlug/video' | '/topics/$topicSlug'
  id:
    | '__root__'
    | '/'
    | '/topics/'
    | '/topics/$topicSlug/video'
    | '/topics/$topicSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  TopicsTopicSlugVideoRoute: typeof TopicsTopicSlugVideoRoute
  TopicsTopicSlugIndexRoute: typeof TopicsTopicSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicSlug/': {
      id: '/topics/$topicSlug/'
      path: '/topics/$topicSlug'
      fullPath: '/topics/$topicSlug/'
      preLoaderRoute: typeof TopicsTopicSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicSlug/video': {
      id: '/topics/$topicSlug/video'
      path: '/topics/$topicSlug/video'
      fullPath: '/topics/$topicSlug/video'
      preLoaderRoute: typeof TopicsTopicSlugVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  TopicsTopicSlugVideoRoute: TopicsTopicSlugVideoRoute,
  TopicsTopicSlugIndexRoute: TopicsTopicSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
